### ISSUE TITLE
need a yolov5 example.

### ISSUE THREAD

**Issue by shownb** [yalue/onnxruntime_go_examples#3]
Hello,
nice example and nice work.
runned a image_object_detect with yolov8 without any problem.

but with a yolov5.onnx
i use the model here:
https://github.com/poojatambe/Yolov5-inference-on-ONNXRuntime-and-opencv-DNN/blob/main/yolov5s.onnx

i run with python without any problem.
but with [onnxruntime_go]
error like that:
```bash
2024-02-13 23:21:30.407649764 [E:onnxruntime:, sequential_executor.cc:514 ExecuteKernel] Non-zero status code returned while running Concat node. Name:'/model.24/Concat_3' Status Message: /onnxruntime_src/onnxruntime/core/framework/execution_frame.cc:171 onnxruntime::common::Status onnxruntime::IExecutionFrame::GetOrCreateNodeOutputMLValue(int, int, const onnxruntime::TensorShape*, OrtValue*&, const onnxruntime::Node&) shape && tensor.Shape() == *shape was false. OrtValue shape verification failed. Current shape:{1,84,8400} Requested shape:{1,25200,85}

panic: Error running network: Non-zero status code returned while running Concat node. Name:'/model.24/Concat_3' Status Message: /onnxruntime_src/onnxruntime/core/framework/execution_frame.cc:171 onnxruntime::common::Status onnxruntime::IExecutionFrame::GetOrCreateNodeOutputMLValue(int, int, const onnxruntime::TensorShape*, OrtValue*&, const onnxruntime::Node&) shape && tensor.Shape() == *shape was false. OrtValue shape verification failed. Current shape:{1,84,8400} Requested shape:{1,25200,85}


goroutine 1 [running]:
main.main()
	/home/noname/onnxruntime/main2.go:76 +0x767
exit status 2

```
Any help is greatly appreciated. 
Thanks.

**Comment by yalue** [comment]
Hello, and thank you for the kind words.

Unfortunately, I did not write the yolov8 example myself, so I am not completely familiar with all of its internals.  However, I think I know the problem in your case: the output tensor is the wrong shape for the yolov5 network.

The yolov8n network produces 1x84x8400 outputs, whereas the yolov5 network produces 1x25200x85 outputs.  The python `onnxruntime` library will detect these shapes and allocate them for you automatically, but the Go code requires that you specify the shapes manually when creating the input and output tensors.

So, to work with yolv5, you'll need to change `image_object_detect/main.cpp` to use the correct shape for the output tensor.  Change:

```go
	// yolov8n version
	outputShape := ort.NewShape(1, 84, 8400)
	outputTensor, err := ort.NewEmptyTensor[float32](outputShape)
```

to

```go
	// yolov5 version
	outputShape := ort.NewShape(1, 25200, 85)
	outputTensor, err := ort.NewEmptyTensor[float32](outputShape)
```

This should allow the neural network to run, but note that you'll also need to modify the code that extracts the bounding boxes and probabilities from the `outputTensor.GetData()` later on.  Since `outputTensor.GetData()` only returns a flattened view of the data, the code currently uses some hardcoded numbers to retrieve the bounding boxes and probabilities from a plain `[]float32`.  Clearly, these numbers will need to change when accessing a flattened view of an output tensor with a different shape.  But I'll leave that up to you!

Maybe one day I'll modify this particular example to bring it more in line with idiomatic go style, but it's not a high priority for me, since it's only intended to showcase one possible use of the onnxruntime_go library and not to serve as a general tool.

**Comment by shownb** [comment]
After several hours of effort, I still haven't solved the problem. I'm not sure where the issue lies.
```golang
	if yolover == "v5" {
		for index := 0; index < 25200; index++ {
			class_id, prob := 0, float32(0.0)
			for col := 0; col < 80; col++ {
				if output[85*index+5+col] > prob {
					prob = output[85*index+5+col]
					class_id = col
				}
			}
			if prob < 0.5 {
				continue
			}
			label := yolo_classes[class_id]
			xc := output[85*index]
			yc := output[85*index+1]
			w := output[85*index+2]
			h := output[85*index+3]
			x1 := (xc - w/2) / 640 * float32(img_width)
			y1 := (yc - h/2) / 640 * float32(img_height)
			x2 := (xc + w/2) / 640 * float32(img_width)
			y2 := (yc + h/2) / 640 * float32(img_height)
			boxes = append(boxes, []interface{}{float64(x1), float64(y1), float64(x2), float64(y2), label, prob})
		}
	}
```

**Comment by yalue** [comment]
I am working on rewriting large parts of this example to be more in line with the conventions used in the other examples.  I don't know if this will help your use case, but I thought I'd notify you at least that the code you're modifying is likely to change, and hopefully it becomes easier to read after the changes.

**Comment by shownb** [comment]
I finally found out what the problem was and now I'm giving ugly code,just to show the problem.
and i have to say that the code of yolov8 example , needs to be improved
```golang
	if yolover == "v5" {
		for index := 0; index < 25200; index++ {
//0.4 is confidenceThreshold
			if output[85*index+4] < 0.4 {
				continue
			}
			class_id, prob := 0, float32(0.0)
			for col := 0; col < 80; col++ {
				if output[85*index+5+col] > prob {
					prob = output[85*index+5+col]
					class_id = col
				}
			}
//0.5 is 
			if prob > 0.5 {
				label := yolo_classes[class_id]
				xc := output[85*index]
				yc := output[85*index+1]
				w := output[85*index+2]
				h := output[85*index+3]
				x1 := (xc - w/2) / 640 * float32(img_width)
				y1 := (yc - h/2) / 640 * float32(img_height)
				x2 := (xc + w/2) / 640 * float32(img_width)
				y2 := (yc + h/2) / 640 * float32(img_height)
				boxes = append(boxes, []interface{}{float64(x1), float64(y1), float64(x2), float64(y2), label, prob})
			}
		}
	}
```
