### ISSUE TITLE
Ask questions, please answer the teacher.

### ISSUE THREAD

**Issue by Nullsssss** [yalue/onnxruntime_go_examples#7]
Now I can run normally, but I am yolov5 model, I need real-time capture screen, so I use github.com/vova616/screenshot this library, but the question didn't seem to occur. And the graphics I put in fit. Can I help you to do a real-time detection screen demo? And would like to ask how I should use the GPU to reason instead of the CPU!! Express one's thanks

**Comment by yalue** [comment]
I'm sorry, but I'm not interested in taking requests for new demos.  If you get one to work, I'd be happy to review a PR to add a working demo to this repo, though!  I don't know why yolov5 isn't working for you.  I'm assuming you've already seen the `image_object_detect` example using yolov8?  The yolov8 example was added by an interested contributor; otherwise the demos in this repo focus on specific portions of the `onnxruntime_go` API rather than applications.

As for why yolov5 isn't working, I strongly suspect the input and/or output formats are not in the correct format---it doesn't matter if the data "fits"; there are still common mistakes regarding how the image is preprocessed.  I would recommend writing a prototype in python using the `onnxruntime` python library.  If the python prototype works, then make sure the flattened view of the input tensors in python matches the flattened view of the input tensor (returned by `Tensor[T].GetData()`) in Go.

**Comment by Nullsssss** [comment]
I read and modify the input and output data, but the image preprocessing is still a problem, I am only a beginner, this is my project. I hope you can help me.

**Comment by yalue** [comment]
I'm sorry, but I don't have enough information or time to help with this.  My recommendation is to make sure you're able to recognize a single image correctly using yolov5 using `onnxruntime` in a python script, since that should be much easier to get working correctly.  After verifying that things work in python, you will have an easier time making sure the inputs and outputs in Go are what you'd expect.  Starting with a single, static image and verifying that you get the expected output is a better starting point than trying to work with live screen captures.
